### ISSUE TITLE
使用本地证书报错

### ISSUE THREAD

**Issue by ChellyL** [RayWangQvQ/naiveproxy-docker#7]
如题，我用其他脚本生成了证书，再使用这个，选择了导入已有证书，在logs里一直显示有问题：
>INFO	using provided configuration	{"config_file": "/data/Caddyfile", "config_adapter": ""}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': /data/Caddyfile:9 - Error during parsing: Wrong argument count or unexpected line ending after '/etc/v2ray-agent/tls/****.key'
Error: caddy process exited with error: exit status 1

请问是因为我改了caddy的端口吗？

docker 和 caddy 的文件如下：

<details>
<summary>docker</summary>

```
version: '3.4'

services:
  naive:
    image: zai7lou/naiveproxy-docker
    container_name: naiveproxy
    tty: true
    restart: unless-stopped
    ports:
      - 38627:38627
      - 23282:23282
    volumes:
      - ./data:/data
      - ./share:/root/.local/share
      - /etc/v2ray-agent/tls/***.crt:/etc/v2ray-agent/tls/***.crt
      - /etc/v2ray-agent/tls/***.key:/etc/v2ray-agent/tls/***.key
```

</details>

<details>
<summary>caddy</summary>

```
{
	debug
	http_port 38627
	https_port 23282
	auto_https disable_certs
	order forward_proxy before file_server
}
:23282, ****.cf {
	tls czKl0j@gmail.com /etc/v2ray-agent/tls/***.crt /etc/v2ray-agent/tls/***.key
	route {
		# proxy
		forward_proxy {
			basic_auth wpZ5Lb X8i8u4/m+DJCVYAAiVg=
			hide_ip
			hide_via
			probe_resistance
		}

		# 伪装网址
		reverse_proxy movie.douban.com {
			header_up Host {upstream_hostport}
		}
	}
}
```
</details>
